### ISSUE TITLE
Remove dotted lines around active a/hyperlink tag

### ISSUE THREAD

**Issue by web-surfer** [TerryZ/v-page#11]
When clicking page change li elements (first, page 1, page 2, etc...) the a tag leaves a dotted outline around the clicked li element like so:

![Pagination a tag outline](https://user-images.githubusercontent.com/17670071/93014124-4a542600-f57c-11ea-941b-74aed72bff86.png)

This happens when a tags/hyperlinks become active.

In the picture, the Page 2 li element is active. But as you can see, the outline only goes around 3 sides of the li element. This is true for all the li elements except the "Last" li element.

I purpose the outline simply be removed like so:

```
.div.v-pagination > ul > li > a {
    outline: none;
}
```

I should note: this happens in Firefox. It does not happen in Chrome.

**Comment by TerryZ** [comment]
OK, understood.

**Comment by TerryZ** [comment]
I tested it with FireFox(80.0), and the dotted outline did not apper when page item active.

**Comment by web-surfer** [comment]
Interesting. It shows up for me in Firefox (81), but not in Chrome. Perhaps it is an issue with my app, then. Please ignore this issue.
