### ISSUE TITLE
How to update page number size 

### ISSUE THREAD

**Issue by aniket-kale** [TerryZ/v-page#13]
Is there any way to update the page number size? As I can see in the docs we can only see 3 or 5 pages at a time. I don't know how we have handled this. but is there any way to update the page number size to 6 or anything else? Please let me know if I am missing anything. Thanks.

![image](https://user-images.githubusercontent.com/35553614/139105066-28d8b6a8-32dc-4b47-a43d-7b192974b611.png)

I have created a demo here. https://codepen.io/aniket-kale/pen/KKvqwZx

**Comment by TerryZ** [comment]
Through debugging the code, it reminds me that this is indeed the original expected design, but maybe your suggestion is more reasonable. The above content will be added in the next version.

**Comment by aniket-kale** [comment]
> Through debugging the code, it reminds me that this is indeed the original expected design, but maybe your suggestion is more reasonable. The above content will be added in the next version.

Hi @TerryZ, When can we expect the next release with this feature? Thanks.

**Comment by TerryZ** [comment]
In this week.

**Comment by TerryZ** [comment]
v-page `v2.0.10` published.

**Comment by aniket-kale** [comment]
Thanks, @TerryZ, It's working perfectly. 🎉 🎉
