### ISSUE TITLE
Page Length

### ISSUE THREAD

**Issue by phanchanra** [TerryZ/v-page#15]
hello guys,
I have seen page length that limit 10, 20, 50, 100, but I want to add one is All that mean, it show all record. 
please tell me can we add?

**Comment by TerryZ** [comment]
So far `v-page` have no support to show all record, because show all record means no need pagination bar.

**Comment by phanchanra** [comment]
Yes When select All option, I use v-page with report but when i print I need this option should support All option one more

**Comment by phanchanra** [comment]
thank you

**Comment by TerryZ** [comment]
Added `displayAll` prop in v-page `v2.1.0`
