### ISSUE TITLE
Error when using in combination with Typescript

### ISSUE THREAD

**Issue by Jogai** [TerryZ/v-page#16]
My linter/compiler errors out when using the latest version. Here I recreated it with only an error in the editor:  https://codesandbox.io/s/vue-typescript-v-page-h9voy3?file=/src/App.vue

`
Module '"v-page"' has no exported member 'Page'. Did you mean to use 'import Page from "v-page"' instead?Vetur(2614)`

**Comment by TerryZ** [comment]
Try `import Page from 'v-page'` and see if it works.

**Comment by TerryZ** [comment]
Issue fixed in `v2.1.0`
