### ISSUE TITLE
how to handle dynamic value?

### ISSUE THREAD

**Issue by rassemdev** [TerryZ/v-page#3]
I have some dynamic data, which is coming from server. I'm using axios to fetch those data. Does your library support pagination for dynamic data. I tried to apply the way you gave me 'codepen demo' from first issue. But in initial load nothing is showing! however if i use static values, the pagination is working fine.

**Comment by TerryZ** [comment]
all you need to do is modify `pagePhotoChange` method，in my demo, `pagePhotoChage` process data based on `v-page` page info returned.

for server side data request, you just need pass page info to server side as parameters, the premise is that you already have page data handle service, for example:

> hypothesis your server side return data format like this
```js
{
    totalRow: 100,
    list:[{...},{...},......]
}
```

the method
```js
pagePhotoChange(pInfo) {
	let that = this;
	axios.post('/xxx/load', pInfo).then(resp=>{	
		that.pagePhoto.totalRow = resp.totalRow;// refresh total row in page bar
		that.pageArr = resp.list;// update new data list
	});
}
```

sorry for my english, hope you can read it.
