### ISSUE TITLE
how to set currentpage

### ISSUE THREAD

**Issue by terwer** [TerryZ/v-page#6]
v-page is a good job,but i find that it can only set totalrow,is there a way to set current page in case of custom invoke pagechange method?

**Comment by TerryZ** [comment]
Why you need to set current page?

**Comment by terwer** [comment]
> Why you need to set current page?

I want to custom refresh data after page inited.

**Comment by okyer** [comment]
Me too, I need to set current page when content page go back list page.

**Comment by TerryZ** [comment]
@terwer Sorry to respond so late, you can do like below to change current page:

```vue
<v-page ref="page"></v-page>
<script>
export default {
    methods: {
        someMethod(){
            // go to the page you want
            this.$refs.page.goPage(3);
        }
    }
}
</script>
```

**Comment by terwer** [comment]
> @terwer Sorry to respond so late, you can do like below to change current page:
> 
> ```
> <v-page ref="page"></v-page>
> <script>
> export default {
>     methods: {
>         someMethod(){
>             // go to the page you want
>             this.$refs.page.goPage(3);
>         }
>     }
> }
> </script>
> ```

Thanks

**Comment by TerryZ** [comment]
You also can user `v-model` to change current page in greater than `v2.0.7` version
