### ISSUE TITLE
Items per page?

### ISSUE THREAD

**Issue by kosciuk** [TerryZ/v-page#8]
If I set page-size-menu="false", how can I set the items per page? Default is 10...

**Comment by TerryZ** [comment]
When set `page-size-mnu` to `false`, the number of pages will always be 10, you want to customize it?

**Comment by kosciuk** [comment]
Yes.... ahhh, I didn't tried with [30] only

**Comment by TerryZ** [comment]
You can try below

```vue
<v-page :page-size-menu="false" ref="page">

// script
mounted () {
  this.$refs.page.pageSize = 30
}
```

**Comment by TerryZ** [comment]
But this is only a transition plan, and will consider use parameter configuration in the future.

**Comment by kosciuk** [comment]
It works! Thanks. 

PD: I notice that @page-change="pageChange" is called on first load 

`<v-page ref="page" :page-size-menu="false" :total-row="42" @page-change="pageChange"></v-page>

// -----------

  methods: {
    pageChange() {
      console.log("pageChange");
    }
  },
  mounted: function() {
    this.$refs.page.pageSize = 30;
  },
`

**Comment by TerryZ** [comment]
What about change lifecycle hook from `mounted` to `beforeMount`

**Comment by kosciuk** [comment]
With beforeMount :

```
this.$refs.page is undefined

```

**Comment by TerryZ** [comment]
So sad...

**Comment by kosciuk** [comment]
I wasn't using v-model, now works fine, thanks. Closing :D
